# Generated by Django 3.0.5 on 2020-04-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_auto_20200424_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='days',
        ),
        migrations.AddField(
            model_name='day',
            name='timesheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timesheets.Timesheet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='start_date',
            field=models.DateField(),
        ),
    ]
